Forum2/ViewModels/ProfileViewModel.cs
using Forum2.Models;

namespace Forum2.ViewModels;

public class ProfileViewModel
{
    public ApplicationUser User { get; set; }
    public List<ApplicationRole>? Roles { get; set; }
    public List<ForumThread>? Threads { get; set; }
    public List<ForumPost>? Posts { get; set; }
}

Forum2/Controllers/MemberController.cs
using Microsoft.AspNetCore.Mvc;

namespace Forum2.Controllers;

public class MemberController : Controller
{
    [HttpGet]
    public IActionResult List()
    {
        return View();
    }
    
    [HttpGet]
    public IActionResult Grid()
    {
        return View();
    }
}

Forum2/Controllers/ProfileController.cs
using Forum2.DAL;
using Forum2.Models;
using Forum2.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Forum2.Controllers;

[Route("Profile/{displayName}")]
public class ProfileController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IForumThreadRepository _forumThreadRepository;
    private readonly IForumPostRepository _forumPostRepository;
    private readonly IWallPostRepository _forumWallPostRepository;
    private readonly IWallPostReplyRepository _forumWallPostReplyRepository;

    public ProfileController(UserManager<ApplicationUser> userManager,
        IForumThreadRepository forumThreadRepository, IForumPostRepository forumPostRepository,
        IWallPostRepository forumWallPostRepository, IWallPostReplyRepository forumWallPostReplyRepository)
    {
        _userManager = userManager;
        _forumThreadRepository = forumThreadRepository;
        _forumPostRepository = forumPostRepository;
        _forumWallPostRepository = forumWallPostRepository;
        _forumWallPostReplyRepository = forumWallPostReplyRepository;
    }

    // For consistency, use the same number of items per page for all lists
    private const int CountPerPage = 10;

    //
    // Profile Wall
    // 
    
    // GET list of wall posts
    [HttpGet]
    [Route("{page?}")]
    public async Task<IActionResult> Index(string displayName, int? page)
    {
        if (string.IsNullOrEmpty(displayName)) return NotFound();
        
        var user = _userManager.Users.FirstOrDefault(u => u.DisplayName == displayName);
        if (user == null) return NotFound();
        
        var wallPosts = await _forumWallPostRepository.GetAllByProfile(user.Id);
        var postsCount = (wallPosts ?? Array.Empty<WallPost>()).Count();
        var totalPages = (int) Math.Ceiling((double) postsCount / CountPerPage);
        var currentPage = page ?? 1;
        var postsToShow = (wallPosts ?? Array.Empty<WallPost>()).Skip((currentPage - 1) * CountPerPage).Take(CountPerPage).ToList();

        var model = new ProfileIndexViewModel()
        {
            User = user,
            CurrentPage = currentPage,
            TotalPages = totalPages,
            WallPosts = postsToShow
        };
        return View(model);
    }

    // GET new wall post form
    [HttpGet]
    [Route("New")]
    [Authorize]
    public Task<IActionResult> NewWallPost(string displayName)
    {
        if (string.IsNullOrEmpty(displayName)) return Task.FromResult<IActionResult>(NotFound());
        
        var user = _userManager.Users.FirstOrDefault(u => u.DisplayName == displayName);
        if (user == null) return Task.FromResult<IActionResult>(NotFound());
        
        var model = new ProfileNewWallPostViewModel
        {
            User = user
        };
        return Task.FromResult<IActionResult>(View(model));
    }
    
    // POST new wall post
    [HttpPost]
    [Route("New")]
    [Authorize]
    public async Task<IActionResult> NewWallPost(string displayName, ProfileNewWallPostViewModel model)
    {
        if (string.IsNullOrEmpty(displayName)) return NotFound();
        
        var profileUser = _userManager.Users.FirstOrDefault(u => u.DisplayName == displayName);
        if (profileUser == null) return NotFound();

        if (!ModelState.IsValid)
        {
            model.User = profileUser;
            return View(model);
        }
        
        var user = await _userManager.GetUserAsync(HttpContext.User);
        if (user == null) return NotFound();
        
        var wallPost = new WallPost
        {
            AuthorId = user.Id,
            ProfileId = profileUser.Id,
            Content = model.Content,
            CreatedAt = DateTime.Now
        };
        
        var result = await _forumWallPostRepository.Create(wallPost);
        if (!result) return StatusCode(500);
        
        return RedirectToAction("Index", new {displayName});
    }
    
    // GET reply to wall post form
    [HttpGet]
    [Route("Reply/{id}")]
    [Authorize]
    public async Task<IActionResult> ReplyWallPost(string displayName, int id)
    {
        if (string.IsNullOrEmpty(displayName)) return NotFound();
        
        var wallPost = await _forumWallPostRepository.GetById(id);
        if (wallPost == null) return NotFound();
        
        var user = _userManager.Users.FirstOrDefault(u => u.DisplayName == displayName);
        if (user == null) return NotFound();
        
        var model = new ProfileReplyWallPostViewModel()
        {
            User = user, 
            WallPostId = id
        };
        return View(model);
    }

    // POST reply to wall post
    [HttpPost]
    [Route("Reply/{id}")]
    [Authorize]
    public async Task<IActionResult> ReplyWallPost(string displayName, int id, ProfileReplyWallPostViewModel model)
    {
        if (string.IsNullOrEmpty(displayName)) return NotFound();
        
        var wallPost = await _forumWallPostRepository.GetById(id);
        if (wallPost == null) return NotFound();
        
        var profileUser = _userManager.Users.FirstOrDefault(u => u.DisplayName == displayName);
        if (profileUser == null) return NotFound();
        
        if (!ModelState.IsValid)
        {
            model.User = profileUser;
            model.WallPostId = id;
            return View(model);
        }
        
        var user = await _userManager.GetUserAsync(HttpContext.User);
        if (user == null) return NotFound();

        var wallPostReply = new WallPostReply
        {
            AuthorId = user.Id,
            WallPostId = id,
            Content = model.Content
        };
        
        var result = await _forumWallPostReplyRepository.Create(wallPostReply);
        if (!result) return StatusCode(500);
        
        return RedirectToAction("Index", new {displayName});
    }

    // POST delete wall post
    [HttpPost]
    [Authorize]
    [Route("/Profile/{displayName}/Delete/{id}")]
    [Authorize]
    public async Task<IActionResult> DeleteWallPost(string displayName, int id)
    {
        if (string.IsNullOrEmpty(displayName)) return NotFound();
        
        var wallPost = await _forumWallPostRepository.GetById(id);
        if (wallPost == null) return NotFound();
        
        var user = await _userManager.GetUserAsync(HttpContext.User);
        var profileUser = await _userManager.FindByIdAsync(wallPost.ProfileId);

        if (HttpContext.User.IsInRole("Moderator") || HttpContext.User.IsInRole("Administrator") || user.Id == wallPost.AuthorId || user.Id == profileUser.Id)
        {
            var result = await _forumWallPostRepository.Delete(id);
            if (!result) return BadRequest();
            return RedirectToAction("Index", new {displayName});
        }

        return StatusCode(500);
    }

    // POST delete wall post reply
    [HttpPost]
    [Authorize]
    [Route("/Profile/{displayName}/DeleteReply/{id}")]
    [Authorize]
    public async Task<IActionResult> DeleteWallPostReply(string displayName, int id)
    {
        if (string.IsNullOrEmpty(displayName)) return NotFound();
        
        var wallPostReply = await _forumWallPostReplyRepository.GetById(id);
        if (wallPostReply == null) return NotFound();
        
        var user = await _userManager.GetUserAsync(HttpContext.User);
        var profileUser = await _userManager.FindByIdAsync(wallPostReply.WallPost.ProfileId);
        
        if (HttpContext.User.IsInRole("Moderator") || HttpContext.User.IsInRole("Administrator") || user.Id == wallPostReply.AuthorId || user.Id == profileUser.Id)
        {
            var result = await _forumWallPostReplyRepository.Delete(id);
            if (!result) return BadRequest();
            return RedirectToAction("Index", new {displayName});
        }
        
        return StatusCode(500);
    }
    
    //
    // Profile Threads
    // 
    
    // GET list of threads
    [HttpGet]
    [Route("/Profile/{displayName}/Threads/{page?}")]
    public async Task<IActionResult> Threads(string displayName, int? page)
    {
        if (string.IsNullOrEmpty(displayName)) return NotFound();
        
        var user = _userManager.Users.FirstOrDefault(u => u.DisplayName == displayName);
        if (user == null) return NotFound();
        
        var threads = await _forumThreadRepository.GetForumThreadsByAccountId(user.Id);
        var orderedThreads = (threads ?? Array.Empty<ForumThread>()).OrderByDescending(x => x.CreatedAt).ToList();
        var threadsCount = orderedThreads.Count;
        var totalPages = (int) Math.Ceiling((double) threadsCount / CountPerPage);
        var currentPage = page ?? 1;
        var threadsToShow = orderedThreads.Skip((currentPage - 1) * CountPerPage).Take(CountPerPage).ToList();
        
        var model = new ProfileThreadsViewModel
        {
            User = user,
            CurrentPage = currentPage,
            TotalPages = totalPages,
            Threads = threadsToShow
        };
        return View(model);
    }
    
    
    //
    // Profile Posts
    // 
    
    // GET list of posts
    [HttpGet()]
    [Route("/Profile/{displayName}/Posts/{page?}")]
    public async Task<IActionResult> Posts(string displayName, int? page)
    {
        if (string.IsNullOrEmpty(displayName)) return NotFound();
        
        var user = _userManager.Users.FirstOrDefault(u => u.DisplayName == displayName);
        if (user == null) return NotFound();
        
        var posts = await _forumPostRepository.GetAllForumPostsByAccountId(user.Id);
        var orderedPosts = (posts ?? Array.Empty<ForumPost>()).OrderByDescending(x => x.CreatedAt).ToList();
        var postsCount = orderedPosts.Count;
        var totalPages = (int) Math.Ceiling((double) postsCount / CountPerPage);
        var currentPage = page ?? 1;

Forum2/Controllers/RoleController.cs
using Forum2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Forum2.Controllers;

public class RoleController : Controller
{
    private readonly RoleManager<ApplicationRole> _roleManager;

    public RoleController(RoleManager<ApplicationRole> roleManager)
    {
        _roleManager = roleManager;
    }

    [HttpGet]
    public IActionResult List()
    {
        return View();
    }
    
    [HttpGet]
    [Route("Role/Members/{roleName}")]
    public IActionResult Members(string roleName)
    {
        var role = _roleManager.FindByNameAsync(roleName).Result;
        return View(role);
    }
}

Forum2/Controllers/SearchController.cs
using Forum2.DAL;
using Forum2.Models;
using Forum2.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Forum2.Controllers;

public class SearchController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IForumThreadRepository _threadRepository;
    private readonly IForumPostRepository _postRepository;
    
    public SearchController(UserManager<ApplicationUser> userManager, IForumThreadRepository threadRepository, 
        IForumPostRepository postRepository)
    {
        _userManager = userManager;
        _threadRepository = threadRepository;
        _postRepository = postRepository;
    }
    
    // For consistency, use the same number of items per page for all lists
    private const int CountPerPage = 10;

    [HttpGet]
    public async Task<IActionResult> Index(string? query)
    {
        var model = new SearchResultViewModel();
        if (query == null) return View(model);
        
        var threads = await _threadRepository.GetAll();
        var posts = await _postRepository.GetAll();
        var users = _userManager.Users.ToList();
        
        // Upper case for case-insensitive search
        var threadsToShow = (threads ?? Array.Empty<ForumThread>())
            .Where(t => t.Title.ToUpper().Contains(query.ToUpper())).Take(CountPerPage).ToList();
        
        var postsToShow = (posts ?? Array.Empty<ForumPost>())
            .Where(p => p.Content.ToUpper().Contains(query.ToUpper())).Take(CountPerPage).ToList();
        
        var usersToShow = users
            .Where(u => u.DisplayName.ToUpper().Contains(query.ToUpper())).Take(CountPerPage).ToList();
        
        model.Query = query;
        model.Threads = threadsToShow;
        model.Posts = postsToShow;
        model.Users = usersToShow;

        return View(model);
    }
    
    [HttpGet]
    [Route("/Search/Threads")]
    public async Task<IActionResult> Threads(string? query, int? page)
    {
        var model = new SearchResultViewModel();
        if (query == null) return View(model);
        
        var threads = await _threadRepository.GetAll();
        
        // Upper case for case-insensitive search
        var threadsRelevant = (threads ?? Array.Empty<ForumThread>())
            .Where(t => t.Title.ToUpper().Contains(query.ToUpper())).ToList();
        
        var threadsCount = threadsRelevant.Count;
        var totalPages = (int) Math.Ceiling((double) threadsCount / CountPerPage);
        var currentPage = page ?? 1;
        var threadsToShow = threadsRelevant.Skip((currentPage - 1) * CountPerPage).Take(CountPerPage).ToList();
        
        model.Query = query;
        model.Threads = threadsToShow;
        model.CurrentPage = currentPage;
        model.TotalPages = totalPages;

        return View(model);
    }

    [HttpGet]
    [Route("/Search/Posts")]
    public async Task<IActionResult> Posts(string? query, int? page)
    {
        var model = new SearchResultViewModel();
        if (query == null) return View(model);
        
        var posts = await _postRepository.GetAll();
        
        // Upper case for case-insensitive search
        var postsRelevant = (posts ?? Array.Empty<ForumPost>())
            .Where(p => p.Content.ToUpper().Contains(query.ToUpper())).ToList();

        var postsCount = postsRelevant.Count;
        var totalPages = (int) Math.Ceiling((double) postsCount / CountPerPage);
        var currentPage = page ?? 1;
        var postsToShow = postsRelevant.Skip((currentPage - 1) * CountPerPage).Take(CountPerPage).ToList();
        
        model.Query = query;
        model.Posts = postsToShow;
        model.CurrentPage = currentPage;
        model.TotalPages = totalPages;

        return View(model);
    }
    
    [HttpGet]
    [Route("/Search/Users")]
    public IActionResult Users(string? query, int? page)
    {
        var model = new SearchResultViewModel();
        if (query == null) return View(model);
        
        var users = _userManager.Users.ToList();
        
        // Upper case for case-insensitive search
        var usersRelevant = users.Where(u => u.DisplayName.ToUpper().Contains(query.ToUpper())).ToList();
        
        var userCount = usersRelevant.Count;
        var totalPages = (int) Math.Ceiling((double) userCount / CountPerPage);
        var currentPage = page ?? 1;
        var usersToShow = usersRelevant.Skip((currentPage - 1) * CountPerPage).Take(CountPerPage).ToList();
        
        model.Query = query;
        model.Users = usersToShow;
        model.CurrentPage = currentPage;
        model.TotalPages = totalPages;

        return View(model);
    }
}

Forum2/Views/Shared/_EditorScriptsPartial.cshtml
<script src="~/lib/easymde/easymde.min.js"></script>

Forum2/Views/Shared/_ForumPostCard.cshtml
@using Westwind.AspNetCore.Markdown
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@model ForumPost

@if (Model.IsSoftDeleted && !User.IsInRole("Administrator"))
{
    <div class="alert alert-secondary mb-4 fst-italic">
        This post has been deleted.
    </div>
}
else
{
    <div class="row mb-4">
        <div class="col-lg-3 mb-2 mb-lg-0">
            <partial name="_Profile" model="UserManager.FindByIdAsync(Model.CreatorId).Result"/>
        </div>
        <div class="col-lg-9">
            <div class="card h-100">
                @if (Model.IsSoftDeleted)
                {
                    <div class="card-header alert-danger d-flex justify-content-between align-items-center">
                        <span>This post is soft deleted.</span>
                        <a class="btn btn-sm btn-danger" asp-controller="ForumPost" asp-action="UnDeleteSelectedForumPost" asp-route-forumPostId="@Model.Id.ToString()">Undelete</a>
                    </div>
                }
                <div id="postContent_@Model.Id.ToString()" class="card-body py-2 d-flex flex-column justify-content-between">
                    <div class="post-content">
                        @Html.Raw(Markdown.Parse(Model.Content, sanitizeHtml: true))
                    </div>

                    <div>
                        @if (Model.EditedAt > Model.CreatedAt)
                        {
                            var editor = UserManager.FindByIdAsync(Model.EditedBy).Result;
                            <span class="text-muted fst-italic" style="font-size: 12px;">
                                Posted on @Model.CreatedAt.ToString("g"), edited by
                                <a asp-controller="Profile" asp-action="Index" asp-route-displayName="@editor.DisplayName" class="text-decoration-none link-dark">
                                    @editor.DisplayName
                                </a>
                                on @Model.EditedAt.ToString("g")
                            </span>
                        }
                        else
                        {
                            <span class="text-muted fst-italic" style="font-size: 12px;">
                                Posted on @Model.CreatedAt.ToString("g")
                            </span>
                        }
                    </div>
                </div>
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="card-footer py-2 px-3">
                        @if (!Model.Thread.IsLocked)
                        {
                            <button class="btn btn-sm btn-dark d-inline" id="quoteThisPost_@Model.Id.ToString()">Quote Post</button>
                        }

                        @if (User.IsInRole("Administrator") || User.IsInRole("Moderator") || UserManager.GetUserAsync(User).Result.Id == Model.CreatorId)
                        {
                            @if (!Model.Thread.IsLocked)
                            {
                                <a class="btn btn-sm btn-dark" asp-controller="ForumPost" asp-action="UpdateForumPostContent" asp-route-forumPostId="@Model.Id.ToString()">Edit Post</a>
                            }
                            @if (!Model.IsSoftDeleted)
                            {
                                <a class="btn btn-sm btn-danger" asp-controller="ForumPost" asp-action="DeleteSelectedForumPost" asp-route-forumPostId="@Model.Id.ToString()">Delete Post</a>
                            }
                        }
                    </div>
                }
            </div>
        </div>
    </div>
}

@if (SignInManager.IsSignedIn(User) && !Model.Thread.IsLocked)
{
    <script>
        @* If input box is not visible, it will be created *@
        async function checkIfInputVisible()
        {
            if (!document.getElementById("createNewForumPost").innerHTML )
            {
                await $.ajax({
                    url: "/ForumPost/Create/@Model.ThreadId.ToString()",
                    success: function (html) {
                        // Update the page with the HTML of the partial view.
                        $("#createNewForumPost").html(html);
                    }
                });
            }
        }
        
        @* Quote handler *@
        async function quotePost()
        {
            await checkIfInputVisible();
            
            let result = "";
            
            const inputField = handleQuoteNewPost(easyMDE.value());
            const quotedPost = parseQuoteIn(" @Model.Content ");
           
            result += inputField;
            result += "Originally posted by @UserManager.FindByIdAsync(Model.CreatorId).Result.DisplayName\n";
            result += quotedPost;
        
            easyMDE.value(result);
            
            @* Hides button to create new post *@
            document.getElementById('createNewForumPostButton').hidden = true;
        }
    
        $("#quoteThisPost_@Model.Id.ToString()").click(quotePost);
    </script>
}

Forum2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Forum2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/tiny-slider/tiny-slider.css"/>
    <link rel="stylesheet" href="~/lib/easymde/easymde.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    
    @* Load jQuery early *@
    <script src="~/lib/jquery/jquery.min.js"></script>
</head>
<body>
<header>
    <partial name="_Navbar" />
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
        @RenderSection("Scripts", required: false)
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Forum2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

Forum2/Views/Shared/_Navbar.cshtml
   <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
       <div class="container-fluid">
           <a class="navbar-brand" asp-controller="Home" asp-action="Index">Forum2</a>
           <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                   aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
           </button>
           <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
               <ul class="navbar-nav flex-grow-1">
                   <li class="nav-item">
                       <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                   </li>
                   <li class="nav-item dropdown">
                       <a class="nav-link dropdown-toggle text-dark" href="#" id="membersDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Members
                       </a>
                       <ul class="dropdown-menu" aria-labelledby="membersDropdown">
                           <li><a class="dropdown-item" asp-controller="Member" asp-action="List">Member List</a></li>
                           <li><a class="dropdown-item" asp-controller="Role" asp-action="List">Role List</a></li>
                       </ul>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link text-dark" asp-controller="ForumCategory" asp-action="ForumCategoryTable">Categories</a>
                   </li>
                   @if (User.IsInRole("Administrator"))
                   {
                       <li class="nav-item">
                           <a class="nav-link text-dark" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                       </li>
                   }
               </ul>
               <form class="d-flex" asp-controller="Search" asp-action="Index" method="get">
                   <input class="form-control form-control-sm me-2" type="text" id="query" name="query" placeholder="Search" required="required">
                   <button class="btn btn-sm btn-outline-success" type="submit">Search</button>
               </form>
               <partial name="_LoginPartial"/>
           </div>
       </div>
   </nav>

Forum2/Views/Shared/_Profile.cshtml
@using Microsoft.AspNetCore.Identity
@inject RoleManager<ApplicationRole> RoleManager
@inject UserManager<ApplicationUser> UserManager

@model ApplicationUser

@{
    var user = UserManager.FindByIdAsync(Model.Id).Result;
    var roles = UserManager.GetRolesAsync(user).Result;
}

<div class="card">
    <div class="card-body">
        <div class="text-center d-flex d-lg-block align-items-center">
            <a asp-controller="Profile"
               asp-action="Index"
               asp-route-displayName="@Model.DisplayName">
                <img class="rounded d-none d-lg-block mx-auto" height="128" width="128" src="~/avatars/@Model.Avatar" alt="@Model.DisplayName"/>
                <img class="rounded d-block d-lg-none me-3" height="32" width="32" src="~/avatars/@Model.Avatar" alt="@Model.DisplayName"/>
            </a>
            <div>
                <a asp-controller="Profile" asp-action="Index" asp-route-displayName="@Model.DisplayName" class="link-dark text-decoration-none">
                    <div class="fw-bold fs-6">@Model.DisplayName</div>
                </a>
            
                @if (roles.Count > 0) {
                    var role = RoleManager.FindByNameAsync(roles[0]).Result;
                    <a asp-controller="Role" asp-action="Members" asp-route-roleName="@role.Name">
                        <div class="badge" style="background: @role.Color;">@role.Name</div>
                    </a>
                } 
                else
                {
                    <div class="badge bg-dark">Member</div>
                }
            </div>
        </div>
    </div>
    <div class="card-footer py-1 py-lg-2">
        <div class="d-flex gap-2 justify-content-md-between" style="font-size:14px;">
            <span>Joined</span>
            <span>@Model.CreatedAt.ToString("d")</span>
        </div>
    </div>
</div>